### ISSUE TITLE
beta9 NoClassDefFoundError: org/jenkinsci/plugins/workflow/job/properties/DurabilityHintJobProperty

### ISSUE THREAD

**Issue by jozef-slezak** [jenkinsci/jenkinsfile-runner#170] opened 2019-10-04 10:43 UTC
Hello, I started jenkinsfile-runner (expanded war, empty plugins dir, https://repo.jenkins-ci.org/releases/io/jenkins/jenkinsfile-runner/jenkinsfile-runner/1.0-beta-9/jenkinsfile-runner-1.0-beta-9-app.zip). I would suggest to create FAT JAR instead (dir containing individual JARs and shell script).

```
bin/jenkinsfile-runner -w ../jenkins-war-2.7.3 -f /mnt/c/tmp/jenkins/ -p ~ -a "param1=Hello"  -a "param2=value2"
2019-10-04 10:39:47.195+0000 [id=1]     SEVERE  h.i.i.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler#uncaughtException: A thread (main/1) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.ClassNotFoundException: org.jenkinsci.plugins.workflow.job.properties.DurabilityHintJobProperty
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Caused: java.lang.NoClassDefFoundError: org/jenkinsci/plugins/workflow/job/properties/DurabilityHintJobProperty
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at io.jenkins.jenkinsfile.runner.JenkinsfileRunnerLauncher.launch(JenkinsfileRunnerLauncher.java:133)
        at io.jenkins.jenkinsfile.runner.App.run(App.java:14)
        at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.run(Bootstrap.java:206)
        at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.main(Bootstrap.java:94)
```

**Comment by oleg-nenashev** [comment] 2019-10-04 11:23
@jozef-slezak yes, having a Fat JAR is something I would like to do. We do it for other Jenkins CLI tools, this project just did not have it historically. Please create a separate issue for it.

Regarding the issue, `DurabilityHintJobProperty` comes from https://github.com/jenkinsci/workflow-job-plugin . The recent versions of this plugin are not compatible with Jenkins 2.7.3 referenced in your startup command, and I assume this is the root cause. You can find the required Jenkins version in the `jenkins.version` property in POM, and for `beta-9` it is 2.176.1. JFR is likely to fail on previous core versions though there is no explicit version check there. I will add a ticket for it

**Comment by oleg-nenashev** [comment] 2019-10-07 08:41
I hit it as well while playing with the Vanilla image demos. Fixing

**Comment by oleg-nenashev** [comment] 2019-10-07 20:30
So the root cause is that JFR does not consult with JARs from the payload when starting the execution. Only plugins dir really counts at that stage... And there is no plugins in @jozef-slezak 's case, Basically I got into the same issue in the Vanilla image. Actually that one just ignores dependencies from pom.xml and installs the recent `declarative-pipeline` plugin and all the recent stuff. I need to look for options, but likely defining the plugins directory is going to be a requirement for now until I figure out the proper classloading sequence for this case

**Comment by oleg-nenashev** [comment] 2019-10-09 11:41
https://github.com/jenkinsci/jenkinsfile-runner/issues/191 for the follow-up about core version checks.

Vanilla packaging was reworked in https://github.com/jenkinsci/jenkinsfile-runner/pull/187, and now there is actually a dump of required plugins generated by it. Later we could add a more complex logic with self-unpacking of plugins for the CLI use

Closing this ticket since the investigation is over IMHO

**Closed as completed by oleg-nenashev** 2019-10-09 11:41 UTC
Labels: bug
